version: '3'
services:
  node-app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/mydb
      - REDIS_URL=redis://redis:6379

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongodb-data:
