name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker build -t your-dockerhub-username/your-nodejs-app:latest .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push your-dockerhub-username/your-nodejs-app:latest

      - name: Run tests
        run: |
          # Add your test commands here
          # For example, npm test

      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          HELM_REPO_URL: ${{ secrets.HELM_REPO_URL }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig.yaml
          kubectl config use-context your-kube-context
          helm repo add my-helm-repo $HELM_REPO_URL
          helm upgrade --install my-nodejs-app my-helm-repo/my-nodejs-chart -f values.yaml --kubeconfig kubeconfig.yaml
